### ISSUE TITLE
Provide error message for empty block: {% %}

### ISSUE THREAD

**Issue by oTree-org** [dmulholl/ibis#4]
```
t = Template("""{% %}""")
res = t.render({})
```

Traceback:

```
Traceback (most recent call last):
  File ".\ibis_test.py", line 23, in <module>
    """)
  File "c:\otree\ibis\ibis\template.py", line 20, in __init__
    self.root_node = compiler.compile(template_string, template_id)
  File "c:\otree\ibis\ibis\compiler.py", line 18, in compile
    return Parser(template_string, template_id).parse()
  File "c:\otree\ibis\ibis\compiler.py", line 166, in parse
    elif token.keyword in nodes.instruction_keywords:
  File "c:\otree\ibis\ibis\compiler.py", line 35, in keyword
    return self.text.split()[0]
IndexError: list index out of range
```

Would be nice if we raised a template syntax error. For example Django templates report:

TemplateSyntaxError: Empty block tag on line 10

**Comment by dmulholl** [comment]
Fixed in `2.0.0-alpha.7`. This used to raise an 'unrecognised tag' error but I outsmarted myself somewhere along the way and broke it. I've added a specific check and error message for empty tags.

Thanks!
